const dresses = [
  {
    id: "1",
    category: "JACKEN",
    categoryID: "1",
    modell: "Kimono",
    productName: "Kimono long",
    produktbeschreibung:
      "This impressive dress is a perfect for a relax start in the day",
    größe: "M",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUUm1tU_J5qyhMKDheop8g2oKlnqbbtVCngQ&s",
    preis: "89,90 €",
    teilenummer: "250512",
    pflege: "30 °C",
    material: "Cotton",
    unikat: "true" /* Unikat */,
    ausverkauft: "false" /* Ausverkauft */,
    lieferzeit: "3-5 Werktage" /* Lieferzeit */,
    versandart: "Standard" /* Versandart */,
    versandkosten: "5,90 €" /* Versandkosten */
  },
  {
    id: "2",
    category: "JACKEN",
    categoryID: "1",
    type: "Kimono" /* Modell */,
    productName: "Kimono Zen",
    produktbeschreibung: "This impressive dress is a perfect for all day use",
    size: "M",
    image:
      "https://shinonyc.com/cdn/shop/products/image_574862cc-9c27-432b-aa6a-ca46b7a094bc_1024x1024@2x.jpg?v=1666017966",
    preis: "99,90 €",
    partnumber: "250512",
    wash_recommendation: "60 °C",
    material: "Cotton 80%, polyester 20%"
  },
  {
    id: "3",
    category: "JACKEN",
    categoryID: "1",
    type: "Kimono",
    productName: "Kimono Allday",
    produktbeschreibung: "This impressive dress is a perfect for all day use",
    size: "M",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7CgousUozfSG17o7n2Mhhnq2qZhgsOYG9i0QBeMOlI7-a8q0OFAOPoyrJifurAVfAS6c&usqp=CAU",
    preis: "79,90 €",
    partnumber: "250512",
    wash_recommendation: "60 °C",
    material: "Cotton"
  },
  {
    id: "4",
    category: "KLEIDER",
    categoryID: "2",
    type: "Kleid",
    productName: "Kleid Allday",
    produktbeschreibung: "This impressive dress is a perfect for all day use",
    size: "M",
    image: "",
    preis: "79,90 €",
    partnumber: "250512",
    wash_recommendation: "60 °C",
    material: "Cotton"
  },
  {
    id: "5",
    category: "ACCESSORIES",
    categoryID: "3",
    type: "Handtasche",
    productName: "Stylish Leather Bag",
    produktbeschreibung: "A stylish leather bag perfect for any occasion.",
    size: "One Size",
    image: "https://example.com/tasche1.jpg",
    preis: "120,00 €",
    partnumber: "350512",
    wash_recommendation: "Do not wash",
    material: "Leather"
  },
  {
    id: "6",
    category: "ACCESSORIES",
    categoryID: "3",
    type: "Rucksack",
    productName: "Durable Canvas Backpack",
    produktbeschreibung: "A durable canvas backpack for everyday use.",
    size: "One Size",
    image: "https://example.com/tasche2.jpg",
    preis: "80,00 €",
    partnumber: "350513",
    wash_recommendation: "Hand wash",
    material: "Canvas"
  },
  {
    id: "7",
    category: "HOSEN",
    categoryID: "4",
    type: "Jeans",
    productName: "Comfortable Denim Jeans",
    produktbeschreibung: "Comfortable denim jeans for casual wear.",
    size: "L",
    image: "https://example.com/hose1.jpg",
    preis: "60,00 €",
    partnumber: "450512",
    wash_recommendation: "40 °C",
    material: "Denim"
  },
  {
    id: "8",
    category: "HOSEN",
    categoryID: "4",
    type: "Chinos",
    productName: "Casual Cotton Pants",
    produktbeschreibung: "Casual cotton pants for everyday wear.",
    size: "L",
    image: "https://example.com/hose2.jpg",
    preis: "70,00 €",
    partnumber: "450513",
    wash_recommendation: "40 °C",
    material: "Cotton"
  },
  {
    id: "9",
    category: "TOPS & BLUSEN",
    categoryID: "5",
    type: "TOPS & BLUSEN",
    productName: "Elegant Silk Blouse",
    produktbeschreibung: "An elegant silk blouse for special occasions.",
    size: "S",
    image: "https://example.com/bluse1.jpg",
    preis: "90,00 €",
    partnumber: "550512",
    wash_recommendation: "Hand wash",
    material: "Silk"
  },
  {
    id: "10",
    category: "TOPS & BLUSEN",
    categoryID: "5",
    type: "TOPS & BLUSEN",
    productName: "Lightweight Polyester Blouse",
    produktbeschreibung: "A lightweight polyester blouse for everyday wear.",
    size: "S",
    image: "https://example.com/bluse2.jpg",
    preis: "50,00 €",
    partnumber: "550513",
    wash_recommendation: "30 °C",
    material: "Polyester"
  },
  // Additional products
  {
    id: "11",
    category: "ACCESSORIES",
    categoryID: "3",
    type: "Clutch",
    productName: "Elegant Evening Clutch",
    produktbeschreibung: "An elegant clutch for evening events.",
    size: "One Size",
    image: "https://example.com/tasche3.jpg",
    preis: "110,00 €",
    partnumber: "350514",
    wash_recommendation: "Do not wash",
    material: "Leather"
  },
  {
    id: "12",
    category: "HOSEN",
    categoryID: "4",
    type: "Leggings",
    productName: "Sporty Leggings",
    produktbeschreibung: "Comfortable leggings for sports and casual wear.",
    size: "M",
    image: "https://example.com/hose3.jpg",
    preis: "40,00 €",
    partnumber: "450514",
    wash_recommendation: "30 °C",
    material: "Polyester"
  },
  {
    id: "13",
    category: "TOPS & BLUSEN",
    categoryID: "5",
    type: "TOPS & BLUSEN",
    productName: "Casual Cotton Blouse",
    produktbeschreibung: "A casual cotton blouse for everyday wear.",
    size: "M",
    image: "https://example.com/bluse3.jpg",
    preis: "45,00 €",
    partnumber: "550514",
    wash_recommendation: "40 °C",
    material: "Cotton"
  },
  {
    id: "14",
    category: "JACKEN",
    categoryID: "1",
    type: "Blazer",
    productName: "Classic Blazer",
    produktbeschreibung: "A classic blazer for formal occasions.",
    size: "L",
    image: "https://example.com/jacke1.jpg",
    preis: "150,00 €",
    partnumber: "250513",
    wash_recommendation: "Dry clean",
    material: "Wool"
  },
  {
    id: "15",
    category: "KLEIDER",
    categoryID: "2",
    type: "Abendkleid",
    productName: "Elegant Evening Dress",
    produktbeschreibung: "An elegant evening dress for special occasions.",
    size: "S",
    image: "https://example.com/kleid1.jpg",
    preis: "200,00 €",
    partnumber: "250514",
    wash_recommendation: "Hand wash",
    material: "Silk"
  },
  {
    id: "16",
    category: "ACCESSORIES",
    categoryID: "3",
    type: "Umhängetasche",
    productName: "Casual Crossbody Bag",
    produktbeschreibung: "A casual crossbody bag for everyday use.",
    size: "One Size",
    image: "https://example.com/tasche4.jpg",
    preis: "90,00 €",
    partnumber: "350515",
    wash_recommendation: "Do not wash",
    material: "Canvas"
  },
  {
    id: "17",
    category: "HOSEN",
    categoryID: "4",
    type: "Shorts",
    productName: "Comfortable Cotton Shorts",
    produktbeschreibung: "Comfortable cotton shorts for casual wear.",
    size: "M",
    image: "https://example.com/hose4.jpg",
    preis: "30,00 €",
    partnumber: "450515",
    wash_recommendation: "40 °C",
    material: "Cotton"
  },
  {
    id: "18",
    category: "TOPS & BLUSEN",
    categoryID: "5",
    type: "TOPS & BLUSEN",
    productName: "Floral Print Blouse",
    produktbeschreibung: "A floral print blouse for a fresh look.",
    size: "M",
    image: "https://example.com/bluse4.jpg",
    preis: "55,00 €",
    partnumber: "550515",
    wash_recommendation: "30 °C",
    material: "Cotton"
  },
  {
    id: "19",
    category: "JACKEN",
    categoryID: "1",
    type: "Bomberjacke",
    productName: "Trendy Bomber Jacket",
    produktbeschreibung: "A trendy bomber jacket for a casual look.",
    size: "L",
    image: "https://example.com/jacke2.jpg",
    preis: "130,00 €",
    partnumber: "250515",
    wash_recommendation: "Dry clean",
    material: "Polyester"
  },
  {
    id: "20",
    category: "KLEIDER",
    categoryID: "2",
    type: "Sommerkleid",
    productName: "Light Summer Dress",
    produktbeschreibung: "A light summer dress perfect for hot days.",
    size: "M",
    image: "https://example.com/kleid2.jpg",
    preis: "70,00 €",
    partnumber: "250516",
    wash_recommendation: "30 °C",
    material: "Cotton"
  },
  {
    id: "21",
    category: "JACKEN",
    categoryID: "1",
    type: "Parka",
    productName: "Winter Parka",
    produktbeschreibung: "A warm parka for cold winter days.",
    size: "L",
    image: "https://example.com/jacke3.jpg",
    preis: "180,00 €",
    partnumber: "250516",
    wash_recommendation: "Dry clean",
    material: "Polyester"
  },
  {
    id: "22",
    category: "KLEIDER",
    categoryID: "2",
    type: "Cocktailkleid",
    productName: "Cocktail Dress",
    produktbeschreibung: "A stylish cocktail dress for evening events.",
    size: "S",
    image: "https://example.com/kleid3.jpg",
    preis: "150,00 €",
    partnumber: "250517",
    wash_recommendation: "Hand wash",
    material: "Silk"
  },
  {
    id: "23",
    category: "ACCESSORIES",
    categoryID: "3",
    type: "Laptop-Tasche",
    productName: "Laptop Bag",
    produktbeschreibung: "A durable laptop bag for work and travel.",
    size: "One Size",
    image: "https://example.com/tasche5.jpg",
    preis: "100,00 €",
    partnumber: "350516",
    wash_recommendation: "Do not wash",
    material: "Nylon"
  },
  {
    id: "24",
    category: "HOSEN",
    categoryID: "4",
    type: "Jogginghose",
    productName: "Jogging Pants",
    produktbeschreibung: "Comfortable jogging pants for sports and leisure.",
    size: "M",
    image: "https://example.com/hose5.jpg",
    preis: "50,00 €",
    partnumber: "450516",
    wash_recommendation: "40 °C",
    material: "Cotton"
  },
  {
    id: "25",
    category: "TOPS & BLUSEN",
    categoryID: "5",
    type: "Seidenbluse",
    productName: "Silk Blouse",
    produktbeschreibung: "A luxurious silk blouse for formal occasions.",
    size: "S",
    image: "https://example.com/bluse5.jpg",
    preis: "95,00 €",
    partnumber: "550516",
    wash_recommendation: "Hand wash",
    material: "Silk"
  }
];

export default dresses;
